name=Klik Line 8
version=1.1.2
author=Vasily Basalaev
maintainer=Amperka <dev@amperka.com>
sentence=A library to interface with the Octoliner 8-channel line sensor.
paragraph=A library to interface with the Octoliner 8-channel line sensor.
category=Device Control
url=https://github.com/Antipat/Klik_line8
architectures=*
